[package]
name = "quadtree"
version = "0.0.4"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "^0.29"
num-traits = "^0.2"
rstar = "^0.12"

[dev-dependencies]
approx = "^0.5"
