[package]
name = "quadtree"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.23.0"
num-traits = "0.2"
rstar = "0.9.3"

[dev-dependencies]
approx = "0.5.1"
